version: "3.9"

services:
  client:
    container_name: user-preference-client
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      # Used at build time by Vite to embed API URL
      VITE_APP_API_URL: ${VITE_APP_API_URL:-http://localhost:8080}
    ports:
      - "4173:4173"
    restart: unless-stopped
