version: "3.8"

services:
    user_preference_dashboard_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: user_preference_dashboard_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./storage:/var/www/storage
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        env_file:
            - .env
        networks:
            - web

    user_preference_dashboard_nginx:
        image: nginx:alpine
        container_name: user_preference_dashboard_nginx
        restart: unless-stopped
        volumes:
            - ./public:/var/www/public
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8080:80"
        depends_on:
            - user_preference_dashboard_app
        networks:
            - web

    user_preference_dashboard_db:
        image: mariadb:10.11
        container_name: user_preference_dashboard_db
        restart: unless-stopped
        labels:
            - "traefik.enable=false"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - user_preference_dashboard_db_data:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - web

networks:
    web:
        external: true


volumes:
    user_preference_dashboard_db_data:
